# keys defined in pyautogui
# Key Settings -> Wildness page

PROMPT_WINDOW_KEY = 'g'
CLAIM_SHARPODONTY_KEY = 'f1'
CLAIM_DUST_KEY = 'f2'
GAIN_CHARACTER_BOND_KEY = 'f3'
HIDE_UI_KEY = 'ctrlleft'
DISPLAY_PALEOHALL_KEY = 'space'

BUY_KEY = 'r'                
LAYOUT_PLAN_KEY = 'tab'      
PLACE_CHARACTERS_KEY = 'c'   
EDIT_WILDERNESS_KEY = 'enter'
MOVE_CAMERA_UP_KEY = 'w'     
MOVE_CAMERA_LEFT_KEY = 'a'   
MOVE_CAMERA_DOWN_KEY = 's'   
MOVE_CAMERA_RIGHT_KEY = 'd'  

TURN_CAMERA_CLOCKWISE_KEY = 'q'
TURN_CAMERA_COUNTERCLOCKWISE_KEY = 'e'